### ISSUE TITLE
Website Roadmap

### ISSUE THREAD

**Issue by LPS100** [LPS100/LPS100.github.io#2]
# Code Workspace
- [ ] Seperate Desktop from Mobile
- [ ] Seperate `root` CSS
- [ ] **RESEARCH** Dark mode variables (AKA how to add native Light-Dark switcher)
- [ ] **RESEARCH** color blind-friendly toggles

# Layout Design
- [ ] Migrate current layout to Tumblr's theme (new repo)
- [ ] Modify layout design for simplicity’s sake
- [ ] Use a readable font for body[^2]
- [ ] Learn flex for the layout[^3]
- [ ] Learn a bit of Java for the gallery[^4]
- [ ] Create pages for:
  - [ ] Illustrations (Traditional & Digital)[^1]
  - [ ] Character Design & Studies
  - [ ] Graphic Design & Iconography 
  - [ ] Who's the Artist
  - [ ] Curriculum Vitae
  - [ ] Contact

## Desktop & Mobile
- [ ] Change layout to a Title Card -> Navbox -> Content
- [ ] Mobile should be below 700px
- [ ] Dektop should be over 700px
- [ ] For your own sake, create a new repo titled FluffTestGround.github.io and use it as a Testing Ground.
- [ ] Inspector Mode and VS's live comparer is your friend.

## Assets
- [ ] Create Content box
- [ ] Create Navbox box
- [ ] Create Title Card
- [ ] Who's the Artist:
  - [ ] Create baby!Edvrian[^5]
  - [ ] Create Edvrian doing art
- [ ] Create basic iconography like arrows and dividers
- [ ] Create Curriculum Vitae

## Readability & Accessibility
- [ ] Add Alt Text on pictures
- [ ] Make sure the contrast isn't too harsh
- [ ] Make sure to use colors that aren't too dark or too light
- [ ] Make sure font is readable
- [ ] For the love of Queen Goddess, DON'T OVER COMPLICATE!!!!

## Other
- [ ] Mention issues such as ADHD in Who's the Artist
- [ ] Add contact info such as main Gmail, Discord, Tumblr, etc
- [ ] !UNSURE! Figure out how to add a section for Story Writing & Development
- [ ] !UNSURE! Figure out how to add a NSFW section with a simple verification (or make a private version of the website)[^6]
---
[^1]: Remember that this is a **PORTFOLIO**, put more focus on showcasing your artwork rather than your pretty face.
[^2]: Candara is great. NOT for bodies. :)
[^3]: Listen, grid is nice, but you can't hide from flex any longer.
[^4]: Same with Java, motherfucker!!!!
[^5]: Privacy is the key.
[^6]: Here's the thing: I do NSFW, but I also want to avoid minors from seeing it. However, it is part of what I can do so... how we gonna solve this, Hoston?
